# Generated by Django 5.0 on 2023-12-08 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blog_author_blog_image_alter_blog_posted_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 14, 57, 47, 730248), verbose_name='Опубликована'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
