# Generated by Django 5.0 on 2023-12-08 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_blog_author_remove_blog_image_alter_blog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 8, 15, 17, 36, 590244), verbose_name='Опубликована'),
        ),
    ]
